---
- name: Run the equivalent of "apt-get update" as a separate step
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  notify:
  - Update all packages to the latest version
  changed_when: true
