server:
    port: 9900
    contextPath: /
    error:
        whitelabel:
            enabled: false
logging:
    file: /var/log/acrs.log

security:
    basic:
        enabled: false
    user:
        name: admin
        password: 123

management:
    context-path: /manage
    security:
        role: SUPERUSER
        enabled: true

redis:
    host: localhost
    port: 6379
    password:
