# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?('nugrant')
  warn "[\e[1m\e[31mERROR\e[0m]: Please run: vagrant plugin install nugrant"
  exit -1
end

BRIDGE_NETWORK = '10.1.0.100'
BRIDGE_NETMASK = '255.255.0.0'

def setup_defaults()
  {
      'appserver' => {
          'name' => 'FortNet - Application Server',
          'cpus' => '1',
          'memory' => '1024',
          'customize' => ['modifyvm', :id,
                          '--nicpromisc2', 'allow-all',
                          '--groups', '/FortNet Reporting System'],
          'gui' => false
      }
  }
end

Vagrant.configure(2) do |config|
  config.user.defaults = setup_defaults

  config.vm.define :fortnet, {:primary => true} do |ah|

    ah.vm.hostname = :appserver
    # ah.vm.provision :docker
    ah.vm.box = 'ubuntu/trusty64'

    ah.vm.synced_folder './../../acontrol-web/src', '/usr/share/nginx/web', :disabled => false # path to application
    ah.vm.synced_folder './../../', '/application-host', :disabled => false # path to application

    ah.vm.network :forwarded_port, guest: 9001, host: 9001 #supervisor
    ah.vm.network :forwarded_port, guest: 6379, host: 6379 #redis
    ah.vm.network :forwarded_port, guest: 8081, host: 8081 #redis-commander
    ah.vm.network :forwarded_port, guest: 9999, host: 9999 #nginx
    ah.vm.network :forwarded_port, guest: 9901, host: 9901 #reporting-api-1
    ah.vm.network :forwarded_port, guest: 9902, host: 9902 #reporting-api-2

    ah.vm.provider :virtualbox do |vb|
      vb.name = config.user.appserver.name
      vb.memory = config.user.appserver.memory
      vb.cpus = config.user.appserver.cpus

      vb.customize config.user.appserver.customize
    end

    # The following line terminates all ssh connections. Therefore
    # Vagrant will be forced to reconnect.
    # That's a workaround to have the docker command in the PATH and
    # add Vagrant to the docker group by logging in/out
    ah.vm.provision :shell, :inline => "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

    ah.vm.provision :ansible do |ansible|
      ansible.playbook = "../application-host.yml"
    end

    ah.vm.provision :ansible do |ansible|
      ansible.playbook = "../slave-host.yml"
    end
  end
end
