---
- name: Create spark worker executor
  sudo: yes
  action: template src=spark-executor.sh.j2 dest="{{ spark_lib_dir }}/spark-executor.sh" mode=0755 group={{ spark_user }} owner={{ spark_user }}

- name: Create supervisord config
  sudo: yes
  action: template src=supervisor-spark-worker.ini.j2 dest="{{ supervisor_conf }}/spark-worker.ini"
  notify:
  - Restarting Supervisor
