---
- name: Create supervisord config
  sudo: yes
  action: template src=etc-supervisor-conf.d-acontrol-report.ini dest="{{ supervisor_conf }}/acontrol-report.ini"
  notify:
  - Restarting Supervisor
