---
- name: Install Nginx
  sudo: yes
  apt:
    name: nginx
    state: present

- name: Stoping Nginx as demon
  sudo: yes
  service:
    name: nginx
    state: stopped
    enabled: no

- name: Create Nginx config
  sudo: yes
  action: template src=etc-nginx-nginx.conf dest=/etc/nginx/nginx.conf

- name: Create web config
  sudo: yes
  action: template src=etc-nginx-sites-enabled-web.conf dest=/etc/nginx/sites-enabled/web.conf

- name: Create supervisord config
  sudo: yes
  action: template src=etc-supervisor-conf.d-nginx.ini dest="{{ supervisor_conf }}/nginx.ini"
  notify:
  - Restarting Supervisor
